ENVIRONMENT: production
SERVER:
  ADDR: ":8080"
  HOST: "localhost:8080"
  READ_TIMEOUT: 5s
  WRITE_TIMEOUT: 10s
  IDLE_TIMEOUT: 120s
DATABASE:
  PATH: "data/vyaya.db"
LOG:
  DIR: "log"
  LEVEL: "info"
