ENVIRONMENT: production
SERVER:
  ADDR: ":8081"
  HOST: "localhost:8081"
  READ_TIMEOUT: 5s
  WRITE_TIMEOUT: 10s
  IDLE_TIMEOUT: 120s
DATABASE:
  PATH: "data/squirrel.db"
LOG:
  DIR: "log"
  LEVEL: "info"
AUTH:
  JWT_SECRET: "a-very-secure-and-shared-secret-key"
  JWT_EXPIRY: 24h
CORS:
  ALLOWED_ORIGINS:
    - "*"
