// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SqrlCategoryColumns holds the columns for the "sqrl_category" table.
	SqrlCategoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "app_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt8, Default: 1},
	}
	// SqrlCategoryTable holds the schema information for the "sqrl_category" table.
	SqrlCategoryTable = &schema.Table{
		Name:       "sqrl_category",
		Columns:    SqrlCategoryColumns,
		PrimaryKey: []*schema.Column{SqrlCategoryColumns[0]},
	}
	// SqrlTransactionColumns holds the columns for the "sqrl_transaction" table.
	SqrlTransactionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "app_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"income", "expense"}},
		{Name: "recurring", Type: field.TypeInt8, Default: 0},
		{Name: "dated", Type: field.TypeTime},
		{Name: "category_id", Type: field.TypeInt, Nullable: true},
	}
	// SqrlTransactionTable holds the schema information for the "sqrl_transaction" table.
	SqrlTransactionTable = &schema.Table{
		Name:       "sqrl_transaction",
		Columns:    SqrlTransactionColumns,
		PrimaryKey: []*schema.Column{SqrlTransactionColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sqrl_transaction_sqrl_category_transactions",
				Columns:    []*schema.Column{SqrlTransactionColumns[9]},
				RefColumns: []*schema.Column{SqrlCategoryColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SqrlCategoryTable,
		SqrlTransactionTable,
	}
)

func init() {
	SqrlCategoryTable.Annotation = &entsql.Annotation{
		Table: "sqrl_category",
	}
	SqrlTransactionTable.ForeignKeys[0].RefTable = SqrlCategoryTable
	SqrlTransactionTable.Annotation = &entsql.Annotation{
		Table: "sqrl_transaction",
	}
}
