basePath: /
definitions:
  internal_category.Category:
    properties:
      app_id:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      status:
        type: integer
      updated_at:
        type: string
      user_id:
        type: integer
    required:
    - name
    type: object
  internal_category.CreateCategoryRequest:
    properties:
      name:
        type: string
      status:
        enum:
        - 0
        - 1
        type: integer
    required:
    - name
    type: object
  internal_category.UpdateCategoryRequest:
    properties:
      name:
        type: string
      status:
        enum:
        - 0
        - 1
        type: integer
    required:
    - name
    type: object
  internal_transaction.CategoryAmountSum:
    properties:
      category_id:
        type: integer
      total_sum:
        type: number
    type: object
  internal_transaction.CreateTransactionRequest:
    properties:
      amount:
        type: number
      category_id:
        type: integer
      dated:
        type: string
      recurring:
        type: integer
      type:
        enum:
        - income
        - expense
        type: string
    required:
    - amount
    - type
    type: object
  internal_transaction.Transaction:
    properties:
      amount:
        type: number
      app_id:
        type: integer
      category_id:
        type: integer
      created_at:
        type: string
      dated:
        type: string
      id:
        type: integer
      recurring:
        type: integer
      type:
        description: income, expense
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  internal_transaction.TransactionListResponse:
    properties:
      stats:
        $ref: '#/definitions/internal_transaction.TransactionStats'
      transactions:
        items:
          $ref: '#/definitions/internal_transaction.Transaction'
        type: array
    type: object
  internal_transaction.TransactionStats:
    properties:
      category_top_10_by_amount_sum:
        items:
          $ref: '#/definitions/internal_transaction.CategoryAmountSum'
        type: array
      category_wise_amount_sum:
        items:
          $ref: '#/definitions/internal_transaction.CategoryAmountSum'
        type: array
      top_10_by_amount:
        items:
          $ref: '#/definitions/internal_transaction.Transaction'
        type: array
    type: object
  internal_transaction.UpdateTransactionRequest:
    properties:
      amount:
        type: number
      category_id:
        type: integer
      dated:
        type: string
      recurring:
        type: integer
      type:
        enum:
        - income
        - expense
        type: string
    required:
    - amount
    - type
    type: object
  vyaya_internal_platform_render.Response:
    properties:
      data: {}
      error:
        type: string
      status:
        type: integer
    type: object
host: localhost:8081
info:
  contact: {}
  description: This is a microservice for expense management.
  title: Vyaya API
  version: "1.0"
paths:
  /categories:
    get:
      description: Get a list of all categories for the authenticated app
      parameters:
      - description: Filter by category name (wildcard)
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/vyaya_internal_platform_render.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/internal_category.Category'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
      security:
      - Bearer: []
      summary: List all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create a new category with the provided name
      parameters:
      - description: Category object
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/internal_category.CreateCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/vyaya_internal_platform_render.Response'
            - properties:
                data:
                  $ref: '#/definitions/internal_category.Category'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
      security:
      - Bearer: []
      summary: Create a new category
      tags:
      - categories
  /categories/{id}:
    delete:
      description: Delete a category by its ID if it belongs to the app
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
      security:
      - Bearer: []
      summary: Delete category by ID
      tags:
      - categories
    get:
      description: Get a single category by its ID if it belongs to the app
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/vyaya_internal_platform_render.Response'
            - properties:
                data:
                  $ref: '#/definitions/internal_category.Category'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
      security:
      - Bearer: []
      summary: Get category by ID
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update an existing category if it belongs to the app
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category object
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/internal_category.UpdateCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/vyaya_internal_platform_render.Response'
            - properties:
                data:
                  $ref: '#/definitions/internal_category.Category'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
      security:
      - Bearer: []
      summary: Update category by ID
      tags:
      - categories
  /health:
    get:
      description: Get the health status of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
      summary: Check service health
      tags:
      - health
  /transactions:
    get:
      description: Get a list of all transactions for the authenticated app with optional
        filtering. Stats in response only include expenses.
      parameters:
      - description: Filter by category ID
        in: query
        name: category_id
        type: integer
      - description: Filter by type (income, expense)
        in: query
        name: type
        type: string
      - description: Filter by recurring status (0 or 1, default 0)
        in: query
        name: recurring
        type: integer
      - description: Filter by predefined date ranges (today, yesterday, this month,
          last month, this year, last year)
        in: query
        name: dated
        type: string
      - description: Filter from date (YYYY-MM-DD)
        in: query
        name: from
        type: string
      - description: Filter to date (YYYY-MM-DD)
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/vyaya_internal_platform_render.Response'
            - properties:
                data:
                  $ref: '#/definitions/internal_transaction.TransactionListResponse'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
      security:
      - Bearer: []
      summary: List all transactions
      tags:
      - transactions
    post:
      consumes:
      - application/json
      description: Create a new transaction with the provided amount, type, category,
        recurring status and dated
      parameters:
      - description: Transaction object
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/internal_transaction.CreateTransactionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/vyaya_internal_platform_render.Response'
            - properties:
                data:
                  $ref: '#/definitions/internal_transaction.Transaction'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
      security:
      - Bearer: []
      summary: Create a new transaction
      tags:
      - transactions
  /transactions/{id}:
    delete:
      description: Delete a transaction by its ID if it belongs to the app
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
      security:
      - Bearer: []
      summary: Delete transaction by ID
      tags:
      - transactions
    get:
      description: Get a single transaction by its ID if it belongs to the app
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/vyaya_internal_platform_render.Response'
            - properties:
                data:
                  $ref: '#/definitions/internal_transaction.Transaction'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
      security:
      - Bearer: []
      summary: Get transaction by ID
      tags:
      - transactions
    put:
      consumes:
      - application/json
      description: Update an existing transaction including amount, type, category,
        recurring status and dated if it belongs to the app
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      - description: Transaction object
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/internal_transaction.UpdateTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/vyaya_internal_platform_render.Response'
            - properties:
                data:
                  $ref: '#/definitions/internal_transaction.Transaction'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
      security:
      - Bearer: []
      summary: Update transaction by ID
      tags:
      - transactions
  /transactions/stats:
    get:
      description: Get statistics for transactions for the authenticated app with
        optional filtering. Only expenses are included.
      parameters:
      - description: Filter by category ID
        in: query
        name: category_id
        type: integer
      - description: Filter by recurring status (0 or 1, default 0)
        in: query
        name: recurring
        type: integer
      - description: Filter by predefined date ranges (today, yesterday, this month,
          last month, this year, last year)
        in: query
        name: dated
        type: string
      - description: Filter from date (YYYY-MM-DD)
        in: query
        name: from
        type: string
      - description: Filter to date (YYYY-MM-DD)
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/vyaya_internal_platform_render.Response'
            - properties:
                data:
                  $ref: '#/definitions/internal_transaction.TransactionStats'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/vyaya_internal_platform_render.Response'
      security:
      - Bearer: []
      summary: Get transaction statistics
      tags:
      - transactions
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
